version: "3.8"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "48291:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "39417:3000"
    depends_on:
      - backend
